name = "ThreadedDenseSparseMul"
uuid = "3d91a4ae-1078-4a13-9dfb-76f34bf57907"
authors = ["Romeo Valentin <romeov@stanford.edu>"]
version = "0.4.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Polyester = "0.7"
StrideArraysCore = "0.5.2 - 0.6"
julia = "1.9"

[extras]
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
StrideArraysCore = "7792a7ef-975c-4747-a70f-980b88e8d1da"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Profile"]
