name = "ThreadedDenseSparseMul"
uuid = "3d91a4ae-1078-4a13-9dfb-76f34bf57907"
authors = ["Romeo Valentin <romeov@stanford.edu>"]
version = "0.2.3"

[deps]
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Polyester = "0.6 - 0.7.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[targets]
test = ["Test", "Profile"]
