name: CI
on:
  push:  # Triggered on push events
    branches:
      - master  # Only runs when pushing to the master branch
    tags: ['*']  # Also runs when any tag is pushed
  pull_request:  # Triggered on pull request events
    branches:
      - master  # Only runs for pull requests targeting the master branch
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '1'
          - '1.10'
          - 'nightly'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          file: lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
